version: "3"

services:
  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - "5432"
    env_file:
      - ./reports-ws/.env
    command: -p 5432

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./reports-web/build:/usr/share/nginx/html
    environment:
    - PRODUCTION=1

  ws:
    image: reports-ws
    build: ./reports-ws
    ports:
      - 5000:5000
    links:
      - database
    depends_on:
      - database
    env_file:
      - ./reports-ws/.env
    volumes:
      - ./reports-ws/:/app
    command: sh /app/deploy.sh