version: "3"

volumes:
  postgres_data: {}

services:
  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - "5432"
    env_file:
      - ./reports-ws/.env
    command: -p 5432

  web:
    image: reports-web
    build: ./reports-web
    ports:
      - 3000:3000
    volumes:
      - ./reports-web/:/app

  ws:
    image: reports-ws
    build: ./reports-ws
    ports:
      - 5000:5000
    links:
      - database
    depends_on:
      - database
    env_file:
      - ./reports-ws/.env
    volumes:
      - ./reports-ws/:/app
    command: sh /app/deploy.sh